version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./audio:/audio
      - ./separated:/separated
    depends_on:
      - spleeter
  spleeter:
    image: researchdeezer/spleeter:2.4.2
    volumes:
      - ./audio:/input
      - ./separated:/output

