version: "3.9"

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - spleeter
    environment:
      - SPLEETER_URL=http://spleeter:8080

  spleeter:
    build: ./spleeter
    ports:
      - "8080:8080"
